[project]
name = "wodeqian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mt-940>=4.30.0",
]

[dependency-groups]
dev = []
